name: absentconsent
favicon: null
layout_spectrum: 0.92331
typography_spectrum: 0.25128
title: in the absence of your consent
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f4ef'
    - '#261d3a'
    - '#9a8687'
    - '#752e3e'
    - '#df4854'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
