name: absentconsent
favicon: null
layout_spectrum: 0.20285
typography_spectrum: 0.2536
title: AbsentConsent
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffc300'
    - '#91c300'
    - '#ffffff'
    - '#00b4f1'
    - '#f8682c'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
